language: go

go:
  - 1.11.x
  - tip

before_install:
  - go get github.com/tsdtsdtsd/identicon
  - go get -v golang.org/x/lint/golint
  # - go get -t -v ./...


script:
  - diff <(gofmt -d .) <(echo -n)
  - go vet -x ./...
  - golint ./...
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)