language: go

go:
  - 1.8.x
  - tip

before_install:
  - go get github.com/tsdtsdtsd/identicon
  - go get -v github.com/golang/lint/golint
  # - go get -t -v ./...


script:
  - diff <(gofmt -d .) <(echo -n)
  - go vet -x ./...
  - golint ./...
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)

  545026a4-ad9d-4094-9777-0c356fc26cdb