name: Tests and Coverage

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.13.x, 1.19.x]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Run tests
        run: make test
      - name: Run coverage
        run: go test -v -coverpkg=./... -coverprofile=coverage.txt -covermode=atomic ./...
      - name: Upload coverage reports to Codecov 
        uses: codecov/codecov-action@v3